### ISSUE TITLE
mobile view - page is tiny, open to single page view

### ISSUE THREAD

**Issue by phette23** [cca/libraries_bookreader#13]
Both phone & tablet sized screens tend to have a very small amount of area devoted to the actual book pages. Some details:

- phone screens should probably open in single-page mode, perhaps using the [jquery.browser](https://github.com/gabceb/jquery-browser-plugin) plugin
- iPad/tablet _should_ be able to handle double pages but the zoom level certainly needs to be adjusted (at least based on Chrome dev tools preview)

## iPad view

_Tiny_ little pages in a vast canvas.

<img width="364" alt="screen shot 2018-09-14 at 10 34 41" src="https://user-images.githubusercontent.com/1024833/45565860-e02c0d80-b809-11e8-8a57-d65ebe062cb8.png">

## iPhone view

This doesn't look as bad as I remember…the Bookreader appears to already intelligently choose a different mode on a smaller screen.

<img width="322" alt="screen shot 2018-09-14 at 10 34 59" src="https://user-images.githubusercontent.com/1024833/45565861-e0c4a400-b809-11e8-9192-ba847a3c1d0b.png">

**Comment by lrayshel** [comment]
yes, that looks good to me as well

LISA CONRAD

Digital Scholarship Librarian


lconrad@cca.edu | 510.594.3733

libraries.cca.edu | vault.cca.edu

Meyer Library, 5212 Broadway | Oakland | CA | 94618

Simpson Library, 1111 Eighth St. | San Francisco | CA | 94107

**Comment by phette23** [comment]
9dec905 seems to have fixed this, closing.
