### ISSUE TITLE
can we put more information in the "About this book" modal dialog?

### ISSUE THREAD

**Issue by phette23** [cca/libraries_bookreader#3]
Click the "i" icon in the upper right to see, currently only shows title. Is there a way we could push more information which would display here?

**Comment by phette23** [comment]
Looks like this is implemented in `bookreader#buildInfoDiv`, ≈ line 5310 of BookReader.js

Maybe we insert out spiel about the Artists' Book Collection there?

**Comment by lrayshel** [comment]
yah, that would be perfect.

Lisa Conrad

Digital Scholarship Librarian

510.594.3733 | lconrad@cca.edu
libraries.cca.edu | vault.cca.edu

Like CCA Libraries on Facebook! http://facebook.com/ccalibrary
